name: flutter_weather_app
description: "A Flutter project for a technical challenge"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_test: ^9.1.5
  copy_with_extension_gen: ^5.0.4
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  http: ^1.2.0
  intl: ^0.19.0
  mockito: ^5.4.4

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/band.jpg
    - assets/cloud.svg
    - assets/forward-right.svg
    - assets/moon.svg
    - assets/sun.svg
    - assets/temperature-high.svg
    - assets/temperature-low.svg
    - assets/weather-rain.svg
    - assets/colors.json
    # this svg was not in the assets
    - assets/error.svg
